CREATE TABLE IF NOT EXISTS User (
  id TEXT NOT NULL PRIMARY KEY,
  fullName TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  documentValue TEXT,
  passwordHash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'CUSTOMER',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Address (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL UNIQUE,
  recipientName TEXT,
  line1 TEXT NOT NULL,
  line2 TEXT,
  district TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  postalCode TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'Brasil',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Category (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  imageUrl TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Product (
  id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  priceInCents INTEGER NOT NULL,
  stock INTEGER NOT NULL,
  featured BOOLEAN NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT 1,
  imageUrl TEXT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  categoryId TEXT NOT NULL,
  FOREIGN KEY (categoryId) REFERENCES Category(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS Cart (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CartItem (
  id TEXT NOT NULL PRIMARY KEY,
  cartId TEXT NOT NULL,
  productId TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (cartId) REFERENCES Cart(id) ON DELETE CASCADE,
  FOREIGN KEY (productId) REFERENCES Product(id) ON DELETE RESTRICT,
  UNIQUE (cartId, productId)
);

CREATE TABLE IF NOT EXISTS "Order" (
  id TEXT NOT NULL PRIMARY KEY,
  orderNumber TEXT NOT NULL UNIQUE,
  userId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'PENDING',
  paymentMethod TEXT NOT NULL,
  shippingName TEXT NOT NULL,
  shippingPhone TEXT,
  shippingDocument TEXT,
  shippingLine1 TEXT NOT NULL,
  shippingLine2 TEXT,
  shippingDistrict TEXT,
  shippingCity TEXT NOT NULL,
  shippingState TEXT NOT NULL,
  shippingPostalCode TEXT NOT NULL,
  shippingCountry TEXT NOT NULL,
  subtotalInCents INTEGER NOT NULL,
  totalInCents INTEGER NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OrderItem (
  id TEXT NOT NULL PRIMARY KEY,
  orderId TEXT NOT NULL,
  productId TEXT,
  productName TEXT NOT NULL,
  imageUrl TEXT NOT NULL,
  unitPriceInCents INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  FOREIGN KEY (orderId) REFERENCES "Order"(id) ON DELETE CASCADE,
  FOREIGN KEY (productId) REFERENCES Product(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS PasswordResetToken (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  tokenHash TEXT NOT NULL UNIQUE,
  expiresAt DATETIME NOT NULL,
  usedAt DATETIME,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Session (
  id TEXT NOT NULL PRIMARY KEY,
  userId TEXT NOT NULL,
  expiresAt DATETIME NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);